### ISSUE TITLE
label, ownerId mandatory, yet are not used

### ISSUE THREAD

**Issue by janvanmansum** [DANS-KNAW/easy-ingest#19]
If you leave out _label_ or _ownerId_ from `cfg.json` this results in a stacktrace (see below). However, if you _do_ specify them, they are not used. (As I recall Fedora seems to have a bug that causes it to ignore a label or ownerId set from parameters in the API calls. See issue #15 ) 

Remove _label_ an _ownerId_ from the possible `cfg.json` settings. Users should set them by including them in `fo.xml`. Update the documentation.

```
Exception in thread "main" org.json4s.package$MappingException: No usable value for ownerId
Did not find value which can be converted into java.lang.String
    at org.json4s.reflect.package$.fail(package.scala:96)
    at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:462)
    at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482)
    at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:482)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$instantiate(Extraction.scala:470)
    at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:515)
    at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:512)
    at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:524)
    at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:512)
    at org.json4s.Extraction$.extract(Extraction.scala:351)
    at org.json4s.Extraction$.extract(Extraction.scala:42)
    at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
    at nl.knaw.dans.easy.ingest.Main$.nl$knaw$dans$easy$ingest$Main$$readDOConfig(Main.scala:105)
    at nl.knaw.dans.easy.ingest.Main$$anonfun$buildConfigDictionary$1.apply(Main.scala:79)
    at nl.knaw.dans.easy.ingest.Main$$anonfun$buildConfigDictionary$1.apply(Main.scala:79)
    at scala.collection.immutable.List.map(List.scala:273)
    at nl.knaw.dans.easy.ingest.Main$.buildConfigDictionary(Main.scala:79)
    at nl.knaw.dans.easy.ingest.Main$.ingestStagedDigitalObjects(Main.scala:68)
    at nl.knaw.dans.easy.ingest.Main$.main(Main.scala:63)
    at nl.knaw.dans.easy.ingest.Main.main(Main.scala)
Caused by: org.json4s.package$MappingException: Did not find value which can be converted into java.lang.String
    at org.json4s.Extraction$.convert(Extraction.scala:603)
    at org.json4s.Extraction$.extract(Extraction.scala:350)
    at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:450)
    ... 24 more
```

**Comment by janvanmansum** [comment]
Done.
